# Generated by Django 5.2.8 on 2025-11-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=5)),
            ],
        ),
    ]
