# Generated by Django 5.2.8 on 2025-11-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_prendas'),
        ),
    ]
