# Generated by Django 5.2.8 on 2025-11-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_prenda_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenda',
            old_name='image',
            new_name='imagen',
        ),
    ]
